### ISSUE TITLE
Ejercicio

### ISSUE THREAD

**Issue by ArielArapa** [ArielArapa/conversor#3]
//Conversor a farenheit
let farenheit = +prompt("Ingrese valor celcius a convertir");
let conversorFarenheit = farenheit*1.8 + 32;
alert("La temeperatura es: " + conversorFarenheit + "ºF.");

//Conversor a celcius
let celcius = +prompt("Ingrese valor farenheit a convertir");
let conversorCelcius = (celcius-32)*0.55;
alert("La temeperatura es: " + conversorCelcius + "ºF.");

**Comment by Carlos-Bustamante** [comment]
okey
